### ISSUE TITLE
Can't load/save the settings file

### ISSUE THREAD

**Issue by zorglube** [basilhendroff/freenas-iocage-rslsync#1]
Hello, 

I followed the manual. 
At the end Resilio Sync is installed, it run, BUT when I login into the Resilio GUI I endup stucked by an "Can't load/save the settings file". 

I'll be happy to purpose any pull-request in order to correct that issue bu I'm not very use to FreeBSD. 
As far as I understand it as something to do with the user creation. 

Also I noticed that, at each start rslsync change the access write of 'settings.dat' and few other files ('history.dat', 'sync.dat', 'http.port', 'sync.lng') 

I order to help my setup is :  FreeNAS-11.3-U4.1 and I'm open to any question if you need clue.

**Comment by basilhendroff** [comment]
Can you post your `rslsync-config`?  Also, check the permissions on `config` and `data` e.g. 

![screenshot 436](https://user-images.githubusercontent.com/63370329/89980601-cb31b080-dca4-11ea-8006-4b1049689216.png)

**Comment by zorglube** [comment]
rslsync-config

`JAIL_IP=192.168.1.51`
`DEFAULT_GW_IP=192.168.1.254`
`POOL_PATH="/mnt/Storage/apps"`
`JAIL_NAME="rslsync"`
`CONFIG_PATH="/mnt/Storage/apps/rslsync/config"`
`DATA_PATH="/mnt/Storage/apps/rslsync/data"`
`INTERFACE="vnet0"`
`VNET="on"`

And 

![2020-08-12 11 07 19 192 168 1 17 e47fc8893af6](https://user-images.githubusercontent.com/630192/89997180-18555880-dc8c-11ea-96d9-3490bd30f4c1.png)

**Comment by basilhendroff** [comment]
I must admit, that's not what I was expecting to see in `/mnt/Storage/apps/rslsync`. While the permissions look right for the `config` and `data` directories, I wasn't expecting to see anything else in the directory. I expected to see something like the screenshot I sent you.

Your `rslsync-config` is also unnecessarily complicated. The defaults will work fine for your use case.
```
JAIL_IP=192.168.1.51
DEFAULT_GW_IP=192.168.1.254
POOL_PATH="/mnt/Storage"
```
If you're able to, I suggest destroying the jail and the `rslsync` directory under `/mnt/Storage/apps`. If you created datasets for these, then just remove the `rslsync` dataset from the pool and set that up again. Then re-run the script after updating `rslsync-config`

![screenshot 440](https://user-images.githubusercontent.com/63370329/90009955-9c7dff00-dcd1-11ea-953b-8be1a6e916b3.png)

**Comment by zorglube** [comment]
It work !! Tank a lot ! 

I have to apologize : my mistake was, I had created an directory '../apps' throught the console, and not an data set throught the 'Storage/Pools' wizard. 

Thank you for your help !
