### ISSUE TITLE
Error trying to run the script on truenas core 12.0 rc

### ISSUE THREAD

**Issue by jhooper94** [basilhendroff/freenas-iocage-rslsync#4]
JAIL_INTERFACES not set, defaulting to: vnet0:bridge0
POOL_PATH defaulting to /mnt/primary
12.2-prerelease was not found!
failed to create jail

If someone could point me in the right direction that would be greatly appreciated.

**Comment by basilhendroff** [comment]
Uncomment line #42 and rerun the script.

`#RELEASE="12.1-RELEASE"`
